### ISSUE TITLE
hash_message wrong when padding_len < n

### ISSUE THREAD

**Issue by bwesterb** [XMSS/xmss-reference#12]
`hash_message` expects the message at offset 4n.  When padding_len < n, then it computes `H(PADDING_HASH || R || Root || 0...0 || M')` instead of `H(PADDING_HASH || R || Root || M)` as described by the NIST draft (where M' is M with last n - padding_len bytes truncated.)

**Comment by bwesterb** [comment]
@dcooper16 ^

**Comment by bwesterb** [comment]
As an aside: I dislike the extra complexity of `padding_len`.  If we are to change the PRFs to be more efficient, I'd much prefer switching to those of SPHINCS+ instead of having this mediocre in-between.

**Comment by joostrijneveld** [comment]
Thanks for spotting this! It's a bit tricky, as `hash_message` relies on a buffer it doesn't allocate for itself, while all the other changes in `hash.c` (7793c40c07483dd3efed0a27a85922ed5c7f0cee) were only local.
