### ISSUE TITLE
Could you provide a set of test vectors separate from the code?

### ISSUE THREAD

**Issue by hallambaker** [XMSS/xmss-reference#5]
I would like to implement in C#. To do this I need test vectors. 

I do not want to look at your code for obvious reasons - I want to see if the spec is clear enough to implement independently.

**Comment by joostrijneveld** [comment]
Thanks for bringing this up! I agree that this would be good to have - it's been on our to-do list for a while.. I'll push it more towards the top of my own stack, and will keep you posted!

**Comment by hallambaker** [comment]
Thanks.

In case you are interested, it is so that I can check the Quantum Secure
recovery box on the new user-centered PKI I am currently working on. This
is where it will fit:

http://mathmesh.com/Documents/draft-hallambaker-mesh-advanced.html


The idea is that if we do hit quantum computing insecurity, then we will
need to switch to symmetric techniques. And having a QCR signature scheme
at least gives us a bootstrap.

My gut feeling is that Quantum computing won't scale. Or at least we are
30-100 years off working out how to make it scale. It may well require
completely different physical principles to keep quantum systems coherent
for macro timescales.

**Comment by joostrijneveld** [comment]
Resolved by #11

**Comment by slontis** [comment]
I am considering adding at least the XMSS-MT verify code path to OpenSSL..
Is there any chance of doing this in a similar manner to the LMS/HSS RFC (See https://www.rfc-editor.org/rfc/rfc8554.html#appendix-F)?
I assume that was what was meant by "Could you provide a set of test vectors separate from the code?"
